### ISSUE TITLE
Extended session management system

### ISSUE THREAD

**Issue by mikron-ia** [mikron-ia/rpg-hub#237]
#30 handles basics of game sessions, but it is far from sufficient. Further work is required:

DB and display:
- [x] Add date, possibly with hour
- [x] Add location

Separate tasks:

- [x] Add roll-out data box, see #235
- [x] Attendance confirmation, removed to #374
- [x] Attendance display, removed to #374

**Comment by mikron-ia** [comment]
Some of those functionalities already exist. Analyze whether this task makes sense and split it as needed.
