### ISSUE TITLE
Switch the epic keeping to links - backend

### ISSUE THREAD

**Issue by mikron-ia** [mikron-ia/rpg-hub#244]
Epic should be kept in the open, not in session. Thus, needed are:

- [ ] front page should aggregate data from epics - see #218
- [ ] `Epic` page should be accessible via `epic/view?key=[key]` and contain epic-specific data
- [ ] Index pages for objects should be accessible via `[object]/index?epic=[key]` and contain epic-specific data
- [ ] View pages for objects should be accessible via `[object]/view?key=[key]` - they need to epic designation as they already belong to one

Breadcrumbs should be like `Home / [epic] / [objects] / [object] / [action]`, where [epic] is derived from key or object data. 

Requires #220 before becoming feasible.
