### ISSUE TITLE
Upgrade `Group` to `Character` level

### ISSUE THREAD

**Issue by mikron-ia** [mikron-ia/rpg-hub#379]
Currently, `Group` looks like `Character`'s underfed cousin - same boxes, same tags, but no search, no sort, etc.

Update `Group` to `Character` level:

- [x] Add `Importance` sorting on frontend (as made operational in #378)
- [x] Add "last updated" sorting on backend
- [x] Add name search
- [x] Add favoriting (as made operational in #253)
- [x] Add importance treatment if done in #134, if not, add `Group` to #134

**Comment by mikron-ia** [comment]
`Group` added to #134. As of this, this task is done.
