### ISSUE TITLE
One-epic environment for backend

### ISSUE THREAD

**Issue by mikron-ia** [mikron-ia/rpg-hub#45]
`Epic` is a closed, self-contained whole, each with their own load od `Person` objects, `Story` objects, `Character` objects, `Recap` objects, and many others. Mixing them on lists is useless, makes another field in index row required (`Epic` name) and serves no purpose.

- [x] Isolate selection to the nav bar
- [x] Filter all content via selected `Epic`
- [x] Store chosen `Epic` in session; it does not have to be stored in DB, it will be enough to use cookie
- [x] Ensure every listable / searchable object is attached to `Epic`
- [x] Consider issues of access rights and visibility in design

Front handling will be done in separate task later.

**Comment by mikron-ia** [comment]
Listability and searchability will be handled by main objects. Descriptions are not concerned with it.

**Comment by mikron-ia** [comment]
For the moment, all `Epic` objects are visible. Their visibility and accessibility will be considered when access control is introduced someday, then it would be prudent to limit their availability, details #60.
